name: expensetracker_isar
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  currency_picker: ^2.0.21
  empty_widget: ^0.0.4
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  insta_image_viewer: ^1.0.4
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  isar_generator: ^3.1.0+1
  path_provider: ^2.1.3
  percent_indicator: ^4.2.3
  riverpod_annotation: ^2.3.5
  salomon_bottom_bar: ^3.3.2
  status_alert: ^1.0.1
  textfield_tags: ^3.0.1
  toggle_switch: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  riverpod_generator:
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true

  assets:
    - assets/
